import Head from 'next/head'
import React from 'react'

export default function HeadComponent() {
  return (
    <Head>
        <title>RevDau | Accelerating Digital India</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  )
}
